name       : libbs2b
version    : 3.1.0
release    : 1
source     :
    - https://downloads.sourceforge.net/project/bs2b/libbs2b/3.1.0/libbs2b-3.1.0.tar.gz : 6aaafd81aae3898ee40148dd1349aab348db9bfae9767d0e66e0b07ddd4b2528
homepage   : https://bs2b.sourceforge.net/
license    : MIT
component  : multimedia.library
summary    : Bauer stereophonic-to-binaural DSP effect library
description: |
    The Bauer stereophonic-to-binaural DSP (bs2b) is designed to improve headphone listening of stereo audio records.
patterns   :
    - utils:
        - /usr/bin
builddeps  :
    pkgconfig(sndfile)
setup      : |
    %configure --enable-static=no
build      : |
    %make
install    : |
    %make_install
